name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the application
        uses: ./.github/actions/build

      - name: Setup actions
        run: pnpm i
        working-directory: ./.github/actions/tag

      - name: Get current tag
        uses: ./.github/actions/tag
        id: get_tag

      - name: Release
        uses: softprops/action-gh-release@v1

        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            product/flat-${{ steps.get_tag.outputs.tag }}.zip
            product/flat-${{ steps.get_tag.outputs.tag }}.exe
            product/app.zip
            product/meta.yaml
          body: |-
            # Flat ${{ steps.get_tag.outputs.tag }}
            ## Download
            - [Windows x64 Potable](https://github.com/ddPn08/flat/releases/download/${{ steps.get_tag.outputs.tag }}/${{ steps.get_tag.outputs.tag }}.exe)
            - [Windows x64 Installer](https://github.com/ddPn08/flat/releases/download/${{ steps.get_tag.outputs.tag }}/${{ steps.get_tag.outputs.tag }}.zip)
